### ISSUE TITLE
Thoughts on folded text block?

### ISSUE THREAD

**Issue by drewgingerich** [google/go-jsonnet#538]
This is cross-posted at [google/jsonnet](https://github.com/google/jsonnet/issues/915).

YAML has folded-style multi-line strings, which means that new-lines are replaced with spaces to end up with a single-line  string. I find this convenient for splitting long shell commands over multiple lines for readability. Does this seem like something potentially good to implement? 

For example and context, I'm looking at using jsonnet to produce YAML Gitlab CI config files. By hand a simplified version looks like this:

```yaml
build:
  stage: build
  only:
    - main
  image: my.kaniko.image
  script:
    - init-kaniko
    - >-
      /kaniko/executor
      --context .
      --dockerfile Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --destination $CI_REGISTRY_IMAGE:latest
```

I really like how I can format the second command in the script block. I think it is very readable and I don't have to fiddle around with escaping new-lines with a `\` like I would in a shell script. I would love to be able to do something similar in jsonnet.
